var validWords=[];
var letters = '';
var discoveredWords =[];
var totalScore = 0;
var pangram = "";

//makes http request to an awi api endpoint that triggers a lambda function to return today's letters/words
//today's words and letters are generated by a lambda function from the valid_words.json dictionary 
function get_valid_words(){

    const url='https://uxxjtb4jz0.execute-api.us-east-1.amazonaws.com/default/FindValidWords';

    var request = new XMLHttpRequest(); 
    request.open('GET', url, true);

    request.onreadystatechange = function(){
        var data = JSON.parse(this.response);
        if(request.readyState == 3 && request.status == 200){
          console.log(data)
          letters = data['letters'];
          validWords = data['possible_words'];
          pangram = data['pangram'];
          initialize_letters();
          
        } else{
          console.log('error')
        };
    };
    request.send();
}


//Creates the hexagon grid of 7 letters with middle letter as special color
function initialize_letters(){
    
    var hexgrid = document.getElementById('hexGrid')
    for(var i=0; i<letters.length; i++){
        var char = letters[i];
        
        var pElement = document.createElement("P");
        pElement.innerHTML = char;
        
        var aElement = document.createElement("A");
        aElement.className = "hexLink";
        aElement.href = "#";
        aElement.appendChild(pElement);
        aElement.addEventListener('click', clickLetter(char), false);

        var divElement = document.createElement('DIV');
        divElement.className = "hexIn"; 
        divElement.appendChild(aElement);
        
        var hexElement = document.createElement("LI");
        hexElement.className = "hex";
        hexElement.appendChild(divElement);
        if(i==3){
          aElement.id = "center-letter";
        }
        hexgrid.appendChild(hexElement);
    }

}

//Validate whether letter typed into input box was from one of 7 available letters
document.getElementById("testword").addEventListener("keydown", function(event){
    if(!letters.includes(event.key.toUpperCase())){
      alert('Invalid Letter Typed')
      event.preventDefault();
    }
  }
  )

//When letter is clicked add it to input box
var clickLetter = function(letter){
  return function curried_func(e){
    var tryword = document.getElementById("testword");
    tryword.value = tryword.value + letter.toLowerCase();
  }
}

//Deletes the last letter of the string in the textbox
function deleteLetter(){
  var tryword = document.getElementById("testword");
  var trywordTrimmed = tryword.value.substring(0, tryword.value.length-1);
  tryword.value = trywordTrimmed;
}

//check if the word is valid and clear the input box
//word must be at least 4 letters
//word must contain center letter
//word can't already be found 
function submitWord(){
  var tryword = document.getElementById('testword');
  var centerLetter = document.getElementById('center-letter').firstChild.innerHTML;

  let score = 0;
  var isPangram = new Boolean(false);
  var showScore = document.getElementById("totalScore");

  if(tryword.value.length < 4){
    alert('Word must be at least 4 characters')
  }else if(discoveredWords.includes(tryword.value.toLowerCase())){
    alert('Word has already been found.')
  }else if(!tryword.value.toLowerCase().includes(centerLetter.toLowerCase())){
    alert('Word doesn\'t contain center letter!');
  }else if(validWords.includes(tryword.value.toLowerCase())){
    isPangram = checkPangram(tryword);
    addToTotalScore(calculateWordScore(tryword, isPangram));
    showScore.innerHTML = totalScore;
    showDiscoveredWord(tryword);
    discoveredWords.push(tryword.value.toLowerCase());
    alert('Valid Word!');
  }else{
    alert('Word Doesn\'t Exist');
  }
  tryword.value = '';
}

//if word was valid, display it 
//if all words are found end game.
function showDiscoveredWord(input){
    var discWords = document.getElementById("discoveredWords");

    var numChildren = discWords.childElementCount; 
    if (numChildren == validWords.length){
      alert("You have found all of the possible words! Thanks for playing");
    } else{
      var listword = document.createElement("LI");
      var pword = document.createElement("P");
      pword.innerHTML = input.value; 
      listword.appendChild(pword);
      discWords.appendChild(listword);
    }
    
}

function addToTotalScore(score) {
  totalScore += score;
}

function calculateWordScore(input, isPangram) {
  let len = input.value.length;
  let returnScore = 1; 
  if(len > 4) {
    returnScore = len;
  }
  if(isPangram) {
    returnScore = len + 7;
  }
  return returnScore;
}

function checkPangram(input) {
  
  var i;
  var containsCount = 0;
  var containsAllLetters = new Boolean(false);
  for(i = 0; i < 7; i++) {
    if(input.value.includes(letters[i])) {
      containsCount++;
    }
  }
  if(containsCount == 7) {
    containsAllLetters = new Boolean(true);
  }
  console.log("isPangram?: " + containsAllLetters);
  return containsAllLetters;
  
  // console.log(input.value);
  // if(input==pangram){
  //  return true;
  // }
 return false;
}

function input_from_keyboard(event) {
  console.log("detected a hit from a key boardy");
    var tryword = document.getElementById("testword");
    tryword.value = tryword.value + String.fromCharCode(event.keyCode).toLowerCase();
    console.log(tryword.value);
}
